---
- name: Configure Nginx Reverse Proxy
  hosts: web_server  
  become: true  

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: latest
    - name: Install pip
      yum:
        name: python3-pip
        state: present
    - name: Install Boto3
      pip:
        name: boto3
        state: present

    - name: Fetch load balancer DNS names
      register: lb_info  # Stores the result
      shell: |
        aws elbv2 describe-load-balancers --names application-tier-lb front-end-lb --output json | jq -r '.LoadBalancers[].DNSName' > lb_dns_names.txt 

    - name: Configure Nginx reverse proxy (with dynamic values)
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx  

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted 
